#!/usr/bin/env bash

if [ $(dpkg-query -W -f='${Status}' libsqlite3-dev 2>/dev/null | grep -c "install ok installed") -eq 0 ];
then
  echo -e 'Required to install libsqlite3-dev'
  sudo apt-get install libsqlite3-dev;
fi


mkdir -p  build && cd build && cmake .. && make


read -n 1 -s -r -p "Press any key to continue"
echo -e ""

cd ..
